M48
; DRILL file {KiCad (6.0.7)} date Mon Nov 21 20:08:11 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-21T20:08:11+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X6.7539Y-4.3744
X6.7539Y-4.602
T2
X4.3071Y-2.9252
X4.3071Y-3.1929
T3
X4.252Y-2.5591
X4.252Y-4.9213
X6.8898Y-2.5591
X6.8898Y-4.9213
T0
M30
