M48
; DRILL file {KiCad (6.0.6)} date Thu Dec  1 22:03:19 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-01T22:03:19+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.3071Y-2.9252
X4.3071Y-3.1929
T2
X4.252Y-2.5591
X4.252Y-4.9213
X6.8898Y-2.5591
X6.8898Y-4.9213
T0
M30
