esphome:
  name: "maker-xmas-tree"

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "maker-xmas-tree"
    password: "zUAmy8OuGzhQ"

captive_portal:

i2c:
  sda: 4
  scl: 5
  scan: true
  id: bus_a

sensor:
  # Battery Level
  - platform: adc
    pin: A0
    name: "Battery Level"
    device_class: battery
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 60s
    filters:
      #- multiply: 6.0 # para obtener en voltios
      - offset: -0.67
      - multiply: 294.12 # (x - min) * 100 / (max - min) -> (x - 0.67) * 100 / (1.0 - 0.67)

  # SHT40 temperature sensor
  - platform: sht4x
    temperature:
      name: "Temperature"
    humidity:
      name: "Relative Humidity"

binary_sensor:
- platform: gpio
  pin: 
    number: 14
    inverted: True
  name: "Change Effect"
  filters:
    - delayed_on: 10ms

switch:
  - platform: gpio
    pin: 13
    name: "LED indicator"
    
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812X
    pin: GPIO12
    num_leds: 12
    name: "NeoPixel Light"
    effects:
      # Use default parameters:
      - random:
      # Customize parameters
      - random:
          name: "My Slow Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "My Fast Random Effect"
          transition_length: 4s
          update_interval: 5s
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
      - pulse:
          name: "Slow Pulse"
          # transition_length: 1s      # defaults to 1s
          update_interval: 2s
      - strobe:
      - strobe:
          name: Strobe Effect With Custom Values
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 90%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              duration: 500ms
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50